server:
  port: 8080
  #tomcat:
    #relaxed-query-chars: "[,]"
  error:
    whitelabel:
      enabled: true
spring:
  application:
      name: MaxKB4j
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cache:
    type: caffeine
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    locations: classpath:db/migration


mybatis-plus:
  global-config:
    db-config:
      capital-mode: false
      table-format: "\"%s\""
      column-format:  "\"%s\""
  mapper-locations: classpath:mapper/**/*.xml,mapper/*.xml
  type-aliases-package: com.tarzan.**.entity
  type-handlers-package: com.tarzan.maxkb4j.common.typehandler
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # jwt秘钥 - 使用环境变量配置
  jwt-secret-key: ${SA_TOKEN_JWT_SECRET_KEY:asdasdasifhueuiwyurfewbfjsdafjk}
  # token 名称（同时也是 cookie 名称）
  token-name: token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 604800
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  # token-style: random-128
  # 是否输出操作日志
  is-log: true
  # 是否读取 Cookie
  is-read-cookie: true
  is-write-header: true


decorator:
  datasource:
    p6spy:
      # 日志格式
      log-format: "\ntime:%(executionTime) || sql:%(sql)\n"
      enable-logging: false

system:
  default-username: admin
  default-password: ${SYSTEM_DEFAULT_PASSWORD:tarzan@123456}